# Linear Algebra

In [1]:
# Library
import numpy as np

# Matrices

In [2]:
matrices = np.array([[1,2,3],[-4,5,6]])

In [3]:
matrices

array([[ 1,  2,  3],
       [-4,  5,  6]])

# Scalars

In [4]:
scalars = 8

In [5]:
scalars

8

# Scalar Array

In [7]:
s_array = np.array(5)

# Vectors

In [12]:
vectors = np.array([7,-8,0])

In [13]:
vectors

array([ 7, -8,  0])

# Data Types

In [14]:
type(matrices)

numpy.ndarray

In [9]:
type(scalars)

int

In [15]:
type(vectors)

numpy.ndarray

In [11]:
type(s_array)

numpy.ndarray

# Data Shapes

In [18]:
matrices.shape

(2, 3)

In [19]:
scalars.shape

AttributeError: 'int' object has no attribute 'shape'

In [20]:
vectors.shape

(3,)

In [21]:
s_array.shape

()

# Data Shapes

In [16]:
matrices.shape

(2, 3)

In [17]:
scalars.shape

AttributeError: 'int' object has no attribute 'shape'

In [ ]:
vectors.shape

In [ ]:
s_array.shape

# Creating a column vector

In [22]:
vectors.reshape(1,3)

array([[ 7, -8,  0]])

In [23]:
vectors.reshape(3,1)

array([[ 7],
       [-8],
       [ 0]])

In [24]:
matrices + scalars

array([[ 9, 10, 11],
       [ 4, 13, 14]])

In [25]:
matrices + s_array

array([[ 6,  7,  8],
       [ 1, 10, 11]])

In [26]:
vectors + scalars

array([15,  0,  8])

In [27]:
vectors + s_array

array([12, -3,  5])

In [28]:
vectors + s_array

array([12, -3,  5])

# Tensors¶

In [29]:
m1 = np.array([[1,2,3],[-4,-5,-6]])
m1

array([[ 1,  2,  3],
       [-4, -5, -6]])

In [30]:
m2 = np.array([[7,8,9],[0,1,2]])
m2

array([[7, 8, 9],
       [0, 1, 2]])

In [31]:
t = np.array([m1,m2])
t

array([[[ 1,  2,  3],
        [-4, -5, -6]],

       [[ 7,  8,  9],
        [ 0,  1,  2]]])